server:
  listen: 8080
  upstreams:
    - id: node1
      url: http://localhost:8001

    - id: node2
      url: http://localhost:8002

    - id: node3 
      url: http://localhost:8003

  paths:
    - path: /
      upstream: node1
    
    - path: /admin
      upstream: node2